language: go

go:
  - tip

script: 
  - curl https://glide.sh/get | sh
  - make install
  - make build
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false